substitutions:
  device_name: waveshare-esp32c6-183

esphome:
  name: ${device_name}

esp32:
  board: esp32-c6-devkitc-1  # Or waveshare variant if available
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf  # Required for C6 displays

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sFpXrDVSs+ZFOs1ow0KRMhp6u3ue93Ml8hgnEFut+Pw="

ota:
  - platform: esphome
    password: "9cb7f620a7735c9765e72c40878049d9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.101
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32W Fallback Hotspot"
    password: "rYJ979MWzAyt"

i2c:
  - sda: GPIO7
    scl: GPIO8
    id: esp32c6_12c

# Display (ST7789 SPI)
spi:
  clk_pin: GPIO1
  mosi_pin: GPIO2

display:
  - platform: ili9xxx
    model: ST7789V
    invert_colors: true
    dimensions: 
      width: 240
      height: 284
      offset_width: 2
      offset_height: 2
    rotation: 0
    cs_pin: GPIO5
    dc_pin: GPIO3
    auto_clear_enabled: false
    update_interval: never
    reset_pin: GPIO4  # Or NO
    id: my_display

touchscreen:
  - platform: cst816
    interrupt_pin: GPIO11
    i2c_id: esp32c6_12c
    id: my_touch
    # Add transform for orientation

output:
  - platform: gpio
    pin: GPIO6
    id: light_out

light:
  - platform: binary  # Local example
    output: light_out
    id: local_light
    on_state: 
      - lvgl.widget.update:
          id: light_sw
          state:
            checked: !lambda 'return id(local_light).current_values.is_on();'
          
binary_sensor:
  - platform: homeassistant  # Remote sync
    entity_id: light.bedroom
    id: ha_light
    on_state:
      - lvgl.widget.update:
          id: light_sw
          state:
            checked: !lambda 'return id(ha_light).state;'

lvgl:
  displays:
    -  my_display
  touchscreens:
    - my_touch
  pages:
    - id: main_page
      bg_color: 0x111827
      widgets:
        - switch:
            id: light_sw
            x: 90
            y: 110
            width: 60
            height: 30
            bg_color: 0x4B5563
            indicator:
              bg_color: 0x4F46E5
            knob:
              bg_color: 0xFFFFFF
              border_color: 0x9CA3AF
              border_width: 1
            on_click:
              - light.toggle: local_light

        - label:
            id: light_label
            x: 70
            y: 150
            width: 100
            height: 30
            text: "Light Switch"
